import 'package:wolog/database/table/equipment.dart';
import 'package:wolog/database/table/exercise_muscle_involvement.dart';
import 'package:wolog/database/table/exercise.dart';
import 'package:wolog/database/table/icon.dart';
import 'package:wolog/database/table/leaning_position.dart';
import 'package:wolog/database/table/muscle_part.dart';
import 'package:wolog/database/table/muscle.dart';
import 'package:wolog/database/table/performance.dart';
import 'package:sqflite/sqflite.dart';