on: [push, pull_request, release, create]
jobs:
  android_job:
    name: "Android"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build apk --release
    - run: dart analyze . || exit 0
    - run: flutter test --coverage
    - name: Coverage report
      uses: coverallsapp/github-action@v2
      with:
        file: coverage/lcov.info
  ios_job:
    name: "iOS"
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
    - run: flutter test
  macos_job:
    name: "macOS"
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: flutter pub get
    - run: flutter config --enable-macos-desktop
    - run: flutter build macos --release
    - run: flutter test

