on: [push, pull_request, release, create]
jobs:
  android_job:
    name: "Android"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter --version
    - run: flutter pub get
    - run: flutter build apk
    - name: 'Upload build release APK'
      uses: actions/upload-artifact@v3
      with:
        name: release Android apk
        path: build/app/outputs/flutter-apk/app-release.apk

